name: flutter_easy_pdfium
description: 'A new Flutter package project.'
version: 0.0.1
homepage: jj

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=1.17.0'

dependencies:
  ffi: ^2.1.2
  flutter:
    sdk: flutter
  flutter_pdfium: ^1.0.2

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter: null
